[2018-10-22T15:16:48.528] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js - 31","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"}}
[2018-10-22T15:16:48.559] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"}}
[2018-10-22T15:17:04.896] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js - 31","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"}}
[2018-10-22T15:17:04.896] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"}}
[2018-10-22T15:25:55.310] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js - 31","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"}}
[2018-10-22T15:25:55.330] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"}}
[2018-10-22T16:53:37.057] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js - 31","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds241699.mlab.com:41699] on first connect [MongoNetworkError: connection 0 to ds241699.mlab.com:41699 timed out]"}}
[2018-10-22T16:53:37.298] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds241699.mlab.com:41699] on first connect [MongoNetworkError: connection 0 to ds241699.mlab.com:41699 timed out]"}}
